---
Name: mysite
After:
  - 'framework/*'
  - 'cms/*'
---
# YAML configuration for SilverStripe
# See http://doc.silverstripe.org/framework/en/topics/configuration
# Caution: Indentation through two spaces, not tabs
SSViewer:
  theme: 'boatsibiza'

Director:
  environment_type: 'dev'

BetterButtonsActions:
  edit:
    Button_Delete: false

BetterButtonsUtils:
  edit:
    Button_New: false
  versioned_edit:
    Button_New: false